---
- hosts: test-nodes
  remote_user: ubuntu
  become: yes
 
  tasks:

  # Install a .deb package from the internet.
  - name: Install a .deb package ( grafana_6.2.2_amd64.deb )
    apt:
      deb: https://dl.grafana.com/oss/release/grafana_6.2.2_amd64.deb

  # Start service 
  - name: Start service grafana-server
    systemd:
      name: grafana-server
      state: started

  # Enable service
  - name: Enable service grafana-server, and not touch the state
    systemd:
      name: grafana-server
      enabled: yes

