---
- hosts: control_node
  become: yes
 
  tasks:

  # Create user 'node_exporter'
  - name: Add the user 'prometheus' with no home dir and no shell
    user:
      name: prometheus
      comment: prometheus
      create_home: no
      shell: /usr/sbin/nologin

  # Create dir at `/etc/prometheus`
  - name: "Create tmp dir at `/etc/prometheus`"
    file:
      state: directory
      path: "/etc/prometheus"
      owner: "prometheus"
      group: "prometheus"

  # Create dir at `/var/lib/prometheus`
  - name: "Create tmp dir at `/var/lib/prometheus`"
    file:
      state: directory
      path: "/var/lib/prometheus"
      owner: "prometheus"
      group: "prometheus"


  # Copy file prometheus to /usr/local/bin/prometheus
  - name: Copy file with owner and permissions
    copy:
      src: "{{  control_base_path }}/tmp/prometheus-2.10.0.linux-amd64/prometheus"
      dest: /usr/local/bin/prometheus
      owner: prometheus
      group: prometheus
      mode: u=rwx,g=rx,o=rx
  # Copy file prometheus to /usr/local/bin/prometheus
  - name: Copy file with owner and permissions
    copy:
      src: "{{  control_base_path }}/tmp/prometheus-2.10.0.linux-amd64/promtool"
      dest: /usr/local/bin/promtool
      owner: prometheus
      group: prometheus
      mode: u=rwx,g=rx,o=rx

  # Copy dir consoles to /etc/prometheus/consoles
  - name: Copy dir consoles to /etc/prometheus/consoles
    copy:
      src: "{{  control_base_path }}/tmp/prometheus-2.10.0.linux-amd64/consoles"
      dest: /etc/prometheus/consoles
      directory_mode:
      owner: prometheus
      group: prometheus
  # Copy dir consoles_libraries to /etc/prometheus/consoles_libraries
  - name: Copy dir consoles_libraries to /etc/prometheus/console_libraries
    copy:
      src: "{{  control_base_path }}/tmp/prometheus-2.10.0.linux-amd64/console_libraries"
      dest: /etc/prometheus/consoles_libraries
      directory_mode:
      owner: prometheus
      group: prometheus

  # Copy file prometheus.yml to /etc/prometheus/prometheus.yml
  - name: Copy file with owner and permissions
    copy:
      src: "{{  control_base_path }}/tmp/prometheus-2.10.0.linux-amd64/prometheus.yml"
      dest: /etc/prometheus/prometheus.yml
      owner: prometheus
      group: prometheus


  # Copy service file to /etc/systemd/system/ dir
  - name: Copy file prometheus.service
    copy:
      src: "{{ control_base_path }}/projects/tools/ansible/cfg/prometheus.service"
      dest: "/etc/systemd/system/prometheus.service"

  # systemd service /etc/systemd/system/prometheus.service
  - name: Start service prometheus
    systemd:
      name: prometheus
      state: started

  # systemd Enable service
  - name: Enable service prometheus, and not touch the state
    systemd:
      name: prometheus
      enabled: yes
