---
- name: Playbook test web
  hosts: all
  tasks:
    # test connection
    - ping: 

    - debug: var=ansible_distribution

# Alternative play
- name: Playbook test web_server
  hosts: all
#  remote_user: nareth
  become: true
  tasks:
    - name: test connection with 'ping' module
      ping:

    - name: debug 'var=ansible_distribution'
      debug: var=ansible_distribution

    - name: Install curl
      apt:
        name: 
          - curl
          - wget
        state: present
      register: pkg_result

    - name: Display pkg_result.
      debug:
        var: pkg_result.stdout
