---
- hosts: managed_nodes
  remote_user: nvidia
  become: yes
 
  tasks:

  # script
  - name: "Packet loss 10% (/home/nvidia/projects/tools/ansible/scripts/tc-packet-loss.sh)"
    script: /home/nvidia/projects/tools/ansible/scripts/tc-packet-loss.sh

