---
- hosts: managed_nodes
  remote_user: nvidia
  become: yes
 
  tasks:

  # script
  - name: /home/nvidia/projects/tools/ansible/scripts/tc-reset.sh 
    script: /home/nvidia/projects/tools/ansible/scripts/tc-reset.sh

