---
- hosts: managed_nodes
  remote_user: nvidia
  become: yes
 
  tasks:

  # script
  - name: "Bandwidth limiting with 'Token Bucket Filtering' (TBF)"
    script: /home/nvidia/projects/tools/ansible/scripts/tc-tbf-1mbit-latency.sh

# ------------------------------------
# Test
# ------------------------------------
#
# Run 'iperf' server on jet-j
# 
#  $ sudo iperf -s -u -i 1
#
#  
# Run 'iperf' client on jet-b
# 
#  $ sudo iperf -c jet-j -u
#
#  

# nvidia@jet-j:~$ sudo iperf -s -u -i 1
# ------------------------------------------------------------
# Server listening on UDP port 5001
# Receiving 1470 byte datagrams
# UDP buffer size:  208 KByte (default)
# ------------------------------------------------------------
# [  3] local 192.168.1.144 port 5001 connected with 192.168.1.131 port 43008
# [ ID] Interval       Transfer     Bandwidth        Jitter   Lost/Total Datagrams
# [  3]  0.0- 1.0 sec   122 KBytes  1000 Kbits/sec   0.868 ms    0/   85 (0%)
# [  3]  1.0- 2.0 sec   119 KBytes   976 Kbits/sec   1.658 ms    2/   85 (2.4%)
# [  3]  2.0- 3.0 sec   119 KBytes   976 Kbits/sec   1.425 ms    6/   89 (6.7%)
# [  3]  3.0- 4.0 sec   113 KBytes   929 Kbits/sec   1.843 ms   10/   89 (11%)
# [  3]  4.0- 5.0 sec   111 KBytes   906 Kbits/sec   1.690 ms   12/   89 (13%)
# [  3]  5.0- 6.0 sec   119 KBytes   976 Kbits/sec   1.883 ms    7/   90 (7.8%)
# [  3]  6.0- 7.0 sec   116 KBytes   953 Kbits/sec   1.606 ms    7/   88 (8%)
# [  3]  7.0- 8.0 sec   118 KBytes   964 Kbits/sec   2.386 ms    8/   90 (8.9%)
# [  3]  8.0- 9.0 sec   118 KBytes   964 Kbits/sec   1.852 ms    7/   89 (7.9%)
# [  3]  9.0-10.0 sec   119 KBytes   976 Kbits/sec   1.499 ms    6/   89 (6.7%)
# [  3]  0.0-10.1 sec  1.16 MBytes   961 Kbits/sec   1.656 ms   66/  893 (7.4%)


# nvidia@jet-b:~/tmp$ sudo iperf -c jet-j -u
# ------------------------------------------------------------
# Client connecting to jet-j, UDP port 5001
# Sending 1470 byte datagrams, IPG target: 11215.21 us (kalman adjust)
# UDP buffer size:  208 KByte (default)
# ------------------------------------------------------------
# [  3] local 192.168.1.131 port 43008 connected with 192.168.1.144 port 5001
# [ ID] Interval       Transfer     Bandwidth
# [  3]  0.0-10.0 sec  1.25 MBytes  1.05 Mbits/sec
# [  3] Sent 893 datagrams
# [  3] Server Report:
# [  3]  0.0-10.1 sec  1.16 MBytes   961 Kbits/sec   0.000 ms   66/  893 (0%)
#

