---
- hosts: managed_nodes
  remote_user: nvidia
  become: yes
 
  tasks:

  # Install a .deb package from the internet.
  - name: /home/nvidia/projects/tools/ansible/scripts/test.sh 
    script: /home/nvidia/projects/tools/ansible/scripts/test.sh

